spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/SpringDataJpa
    username: admin
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true # 쿼리가 한줄로 나오는게 아니라 포매팅을 해서 보기 좋게 나오게 한다.

logging.level:
  org.hibernate.SQL: debug # show_sql: true를 콘솔이 아닌 로그파일로 남길 수 있다.
  org.hibernate.type: trace # 파라미터 바인딩시의 파라미터 까지 볼 수 있게 해준다. ? 가 안나오게 된다.
